FROM liquibase/liquibase
ADD migrations/ /liquibase/changelog

CMD ["sh", "-c", "docker-entrypoint.sh --url=jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB} --username=${POSTGRES_USERNAME} --password=${POSTGRES_PASSWORD} --classpath=/liquibase/changelog --changeLogFile=liquibase/changelog/migrations.yaml update"]
